recipe: default.v1
language: en
pipeline:

- name: "SpacyNLP"
  model: "en_core_web_md"

- name: SpacyTokenizer

#- name: WhitespaceTokenizer

- name: CountVectorsFeaturizer

- name: LanguageModelFeaturizer
  model_name: bert
  model_weights: rasa/LaBSE

- name: DIETClassifier
  epochs: 100
  constrain_similarities: true

- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 100
  constrain_similarities: true

- name: FallbackClassifier
  threshold: 0.7
  ambiguity_threshold: 0.1

policies:
- name: RulePolicy
- name: MemoizationPolicy
- name: TEDPolicy
  epochs: 20
  max_history: 10
assistant_id: 20230420-124639-stale-marina
